In [ ]:
from lightning_model import LightningClassicGNN

LightningClassicGNN.load_from_checkpoint("../training_artifacts/test-project/1djimtqv/checkpoints/epoch=0-step=29.ckpt")

In [55]:
from sklearn.metrics import roc_auc_score
import numpy as np
import torch.nn.functional as F
import torch



y_true=torch.tensor([0,0,1])
y_score=torch.tensor([[3,1],[3,1],[1,3]]).float()

y_prob = F.softmax(input=y_score,dim=1)[:,1]

print(y_prob)


roc_auc_score(y_true=y_true, y_score=y_prob)


tensor([0.1192, 0.1192, 0.8808])


1.0

In [2]:
from datasets_classes import QM9Dataset

dataset = QM9Dataset(root="../old_data/qm9/")

In [27]:
from sklearn.model_selection import StratifiedShuffleSplit
import numpy as np
import torch

idx = [0,100,50]

dataset[idx]

QM9Dataset(3)

In [45]:
y1 = [data.y.numpy() for data in dataset[:2]]
y2 = [data.y.numpy() for data in dataset[2:4]]

In [44]:
y1

[array([  0.      ,  13.21    ,  -0.3877  ,   0.1171  ,   0.5048  ,
         35.3641  ,   0.044749, -40.47893 , -40.476062, -40.475117,
        -40.498597,   6.469   ]),
 array([ 1.6256000e+00,  9.4600000e+00, -2.5700000e-01,  8.2900000e-02,
         3.3990000e-01,  2.6156300e+01,  3.4358000e-02, -5.6525887e+01,
        -5.6523026e+01, -5.6522082e+01, -5.6544961e+01,  6.3160000e+00])]

In [41]:
y = []

y + y1 + y2

[array([[  0.      ,  13.21    ,  -0.3877  ,   0.1171  ,   0.5048  ,
          35.3641  ,   0.044749, -40.47893 , -40.476062, -40.475117,
         -40.498597,   6.469   ]]),
 array([[ 1.6256000e+00,  9.4600000e+00, -2.5700000e-01,  8.2900000e-02,
          3.3990000e-01,  2.6156300e+01,  3.4358000e-02, -5.6525887e+01,
         -5.6523026e+01, -5.6522082e+01, -5.6544961e+01,  6.3160000e+00]]),
 array([[ 1.8511000e+00,  6.3100000e+00, -2.9280000e-01,  6.8700000e-02,
          3.6150000e-01,  1.9000200e+01,  2.1375000e-02, -7.6404702e+01,
         -7.6401867e+01, -7.6400922e+01, -7.6422349e+01,  6.0020000e+00]]),
 array([[ 0.0000000e+00,  1.6280000e+01, -2.8450000e-01,  5.0600000e-02,
          3.3510000e-01,  5.9524800e+01,  2.6841000e-02, -7.7308427e+01,
         -7.7305527e+01, -7.7304583e+01, -7.7327429e+01,  8.5740000e+00]])]

In [39]:
y1

[array([[  0.      ,  13.21    ,  -0.3877  ,   0.1171  ,   0.5048  ,
          35.3641  ,   0.044749, -40.47893 , -40.476062, -40.475117,
         -40.498597,   6.469   ]]),
 array([[ 1.6256000e+00,  9.4600000e+00, -2.5700000e-01,  8.2900000e-02,
          3.3990000e-01,  2.6156300e+01,  3.4358000e-02, -5.6525887e+01,
         -5.6523026e+01, -5.6522082e+01, -5.6544961e+01,  6.3160000e+00]])]

In [46]:
import pandas as pd

df = pd.read_csv("../data/bace/raw/bace.csv")

df.Class.isna().sum()

0

In [ ]:

import torch
torch.load("../data/bace/processed/aux_data.pt")

In [ ]:
from utils import download_dataset

download_dataset(raw_dir="../data/freesolv/raw", filename='freesolv.csv.gz',raw_url='https://deepchemdata.s3.us-west-1.amazonaws.com/datasets/freesolv.csv.gz', target_columns=["y"], data_column_name="smiles")

In [1]:
from datasets_classes import BaceDataset

dataset = BaceDataset(root="../old_data/bace/", add_hydrogen=True)


dataset[1], dataset[1].y, dataset[1].idx

Processing...

KeyboardInterrupt



In [ ]:
import torch

(data, slices) = torch.load("../data/bbbp/processed/BBBP.pt")

In [5]:
import pandas as pd

df = pd.read_csv("../old_data/bbbp/raw/BBBP.csv",index_col=0, encoding="utf-8")
original_data = df.index
target = torch.tensor(df.values)

In [25]:
df

p_np
smiles                                                  
[Cl].CC(C)NCC(O)COc1cccc2ccccc12                       1
C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl               1
c12c3c(N4CCN(C)CC4)c(F)cc1c(c(C(O)=O)cn2C(C)CO3)=O     1
C1CCN(CC1)Cc1cccc(c1)OCCCNC(=O)C                       1
Cc1onc(c2ccccc2Cl)c1C(=O)N[C@H]3[C@H]4SC(C)(C)[...     1
...                                                  ...
C1=C(Cl)C(=C(C2=C1NC(=O)C(N2)=O)[N+](=O)[O-])Cl        1
[C@H]3([N]2C1=C(C(=NC=N1)N)N=C2)[C@@H]([C@@H]([...     1
[O+]1=N[N](C=C1[N-]C(NC2=CC=CC=C2)=O)C(CC3=CC=C...     1
C1=C(OC)C(=CC2=C1C(=[N+](C(=C2CC)C)[NH-])C3=CC=...     1
[N+](=NCC(=O)N[C@@H]([C@H](O)C1=CC=C([N+]([O-])...     1

[2050 rows x 1 columns]

In [30]:
from datasets_classes import FreeSolvDataset, BBBPDataset, BaceDataset
import torch
import os.path as osp

dataset = FreeSolvDataset(root="../old_data/freesolv")
dataset = BBBPDataset(root="../data/bbbp/")
dataset = BaceDataset(root="../data/bace/", add_hydrogen=True)

In [35]:
from pymatgen.core import Structure

Structure.distance_matrix

torch.Size([1513])

In [10]:
from ucr_lightning_data_module import UcrDataModule
import numpy as np


data_module = UcrDataModule(dataset=dataset, seed=42, stratified=True)

train_y = np.array([data.y for data in data_module.train_data])
valid_y = np.array([data.y for data in data_module.valid_data])

train_y.sum() / train_y.shape[0], valid_y.sum() / valid_y.shape[0], train_y.sum() / train_y.shape[0], 

Global seed set to 42
/tmp/ipykernel_12487/1078495735.py:7: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  train_y = np.array([data.y for data in data_module.train_data])
/tmp/ipykernel_12487/1078495735.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  train_y = np.array([data.y for data in data_module.train_data])
/tmp/ipykernel_12487/1078495735.py:8: FutureWarnin

(tensor([[0.7651]]), tensor([[0.7635]]))

In [2]:
from sklearn.model_selection import StratifiedShuffleSplit
import numpy as np
y= dataset.y.numpy()

x = np.arange(y.shape[0])

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.4, random_state=42)

train_index , test_index = [i for i in sss.split(x,y)][0]



In [22]:
list(sss.split(x,y))[0]

(array([1764, 1612,   53, ..., 1288,  943, 1085]),
 array([ 600, 1787, 1490, 1964, 1831,  874,  110,   97, 1211, 1131, 1226,
        1822,  202,  101, 1527,  139,  162, 1844,  963,  111, 1216, 1466,
         472,  318, 1316, 1939,  532,  916,  245, 1213,  503,  251,  586,
         155,  190,  295, 1177, 1941, 2036,  217,  870,  612,  977, 1305,
         589, 1899, 1928, 1867,  203,  939, 1126, 1994,  981,  750,   41,
         727, 1052, 1683,  623, 1390, 1841,   15, 1192,  598, 1602, 1670,
         264, 1858,  408, 1329, 1866,  840, 2017, 1207, 1425,  189, 1380,
        1863, 1625, 1745, 1830, 1103,  390,  558, 1967,  260,  392,  802,
        1897,   94,  263,  667,  685, 1301, 1105,  854, 1160, 2034, 1646,
        1692, 1396,  122,  456,  421,  180, 1575, 1597, 1624, 1397,  996,
           0,  776, 1886,  289, 1666, 1528,  516, 1437, 1398, 1711, 1699,
        1619, 1278, 1331, 1684,  659, 1651, 1706, 1893,  787, 1671,  932,
         924, 1981, 1613, 1705, 1572,  784,  832, 1095,  651,

array([   0,    1,    2, ..., 2034, 2035, 2036])

In [7]:
dataset.y == torch.tensor(df.values)

tensor([False, False, False,  ..., False, False, False])

In [ ]:
from datasets_classes import FreeSolvDataset

dataset = FreeSolvDataset(root="../data/freesolv/")

dataset[0]

In [8]:
from datasets_classes import QM9Dataset

dataset = QM9Dataset(root="../old_data/qm9/")

dataset[1]

Data(x=[1, 5], edge_index=[2, 0], edge_attr=[0, 5], y=[1, 12], pos=[4, 3], z=[1], name='N', idx=1)

In [ ]:
import os.path as osp
import torch

for data_split_idx in range(2):

    data_list = torch.load(osp.join("../data/matbench/mp_is_metal",f"mp_is_metal.json_{data_split_idx}.pt"))
    for i,data in enumerate(data_list):
        if i == 0:
            print(data.y)
            print(data)
            data.y = torch.tensor([0.0]).view(-1,1)
            print(data)            
            print(data.y)
        

tensor([[  0.0000,  13.2100,  -0.3877,   0.1171,   0.5048,  35.3641,   0.0447,
         -40.4789, -40.4761, -40.4751, -40.4986,   6.4690]],
       dtype=torch.float64)
Data(x=[1, 5], edge_index=[2, 0], edge_attr=[0, 5], y=[1, 12], pos=[5, 3], z=[1], name='C', idx=0)
Data(x=[1, 5], edge_index=[2, 0], edge_attr=[0, 5], y=[1, 1], pos=[5, 3], z=[1], name='C', idx=0)
tensor([[0.]])
tensor([[ 9.2180e-01,  7.1030e+01, -2.4210e-01,  4.1700e-02,  2.8390e-01,
          1.4473e+03,  1.4597e-01, -3.0968e+02, -3.0967e+02, -3.0967e+02,
         -3.0972e+02,  2.9903e+01]], dtype=torch.float64)
Data(x=[7, 5], edge_index=[2, 42], edge_attr=[42, 5], y=[1, 12], pos=[17, 3], z=[7], name='CCC#CCOC', idx=2677)
Data(x=[7, 5], edge_index=[2, 42], edge_attr=[42, 5], y=[1, 1], pos=[17, 3], z=[7], name='CCC#CCOC', idx=2677)
tensor([[0.]])
