In [ ]:
from lightning_model import LightningClassicGNN

LightningClassicGNN.load_from_checkpoint("../training_artifacts/test-project/1djimtqv/checkpoints/epoch=0-step=29.ckpt")

In [55]:
from sklearn.metrics import roc_auc_score
import numpy as np
import torch.nn.functional as F
import torch



y_true=torch.tensor([0,0,1])
y_score=torch.tensor([[3,1],[3,1],[1,3]]).float()

y_prob = F.softmax(input=y_score,dim=1)[:,1]

print(y_prob)


roc_auc_score(y_true=y_true, y_score=y_prob)


tensor([0.1192, 0.1192, 0.8808])


1.0

In [ ]:
from datasets_classes import QM9Dataset

dataset = QM9Dataset(root="../data/qm9/")

In [46]:
import pandas as pd

df = pd.read_csv("../data/bace/raw/bace.csv")

df.Class.isna().sum()

0

In [ ]:

import torch
torch.load("../data/bace/processed/aux_data.pt")

In [ ]:
from utils import download_dataset

download_dataset(raw_dir="../data/freesolv/raw", filename='freesolv.csv.gz',raw_url='https://deepchemdata.s3.us-west-1.amazonaws.com/datasets/freesolv.csv.gz', target_columns=["y"], data_column_name="smiles")

In [7]:
from datasets_classes import BaceDataset

dataset = BaceDataset(root="../data/bace/", add_hydrogen=True)


dataset[1], dataset[1].y, dataset[1].idx

(Data(x=[98, 22], edge_index=[2, 9506], edge_attr=[9506, 3], y=[1, 2], pos=[98, 3], z=[98], name='Fc1cc(cc(F)c1)C[C@H](NC(=O)[C@@H](N1CC[C@](NC(=O)C)(CC(C)C)C1=O)CCc1ccccc1)[C@H](O)[C@@H]1[NH2+]C[C@H](OCCC)C1', idx=[1]),
 tensor([[1.0000, 8.8539]], dtype=torch.float64),
 tensor([1]))

In [ ]:
import torch

(data, slices) = torch.load("../data/bbbp/processed/BBBP.pt")

In [ ]:
slices

In [4]:
from datasets_classes import BBBPDataset

dataset = BBBPDataset(root="../old_data/bbbp/")

dataset[0]

Data(x=[20, 5], edge_index=[2, 380], edge_attr=[380, 5], y=[1, 1], pos=[41, 3], z=[20], name='[Cl].CC(C)NCC(O)COc1cccc2ccccc12', idx=[1])

In [ ]:
from datasets_classes import FreeSolvDataset

dataset = FreeSolvDataset(root="../data/freesolv/")

dataset[0]

In [8]:
from datasets_classes import QM9Dataset

dataset = QM9Dataset(root="../old_data/qm9/")

dataset[1]

Data(x=[1, 5], edge_index=[2, 0], edge_attr=[0, 5], y=[1, 12], pos=[4, 3], z=[1], name='N', idx=1)

In [15]:
import os.path as osp
import torch

for data_split_idx in range(2):

    data_list = torch.load(osp.join("../old_data/qm9/processed/",f"qm9_{data_split_idx}.pt"))
    for i,data in enumerate(data_list):
        if i == 0:
            print(data.y)
            print(data)
            data.y = torch.tensor([0.0]).view(-1,1)
            print(data)            
            print(data.y)
        

tensor([[  0.0000,  13.2100,  -0.3877,   0.1171,   0.5048,  35.3641,   0.0447,
         -40.4789, -40.4761, -40.4751, -40.4986,   6.4690]],
       dtype=torch.float64)
Data(x=[1, 5], edge_index=[2, 0], edge_attr=[0, 5], y=[1, 12], pos=[5, 3], z=[1], name='C', idx=0)
Data(x=[1, 5], edge_index=[2, 0], edge_attr=[0, 5], y=[1, 1], pos=[5, 3], z=[1], name='C', idx=0)
tensor([[0.]])
tensor([[ 9.2180e-01,  7.1030e+01, -2.4210e-01,  4.1700e-02,  2.8390e-01,
          1.4473e+03,  1.4597e-01, -3.0968e+02, -3.0967e+02, -3.0967e+02,
         -3.0972e+02,  2.9903e+01]], dtype=torch.float64)
Data(x=[7, 5], edge_index=[2, 42], edge_attr=[42, 5], y=[1, 12], pos=[17, 3], z=[7], name='CCC#CCOC', idx=2677)
Data(x=[7, 5], edge_index=[2, 42], edge_attr=[42, 5], y=[1, 1], pos=[17, 3], z=[7], name='CCC#CCOC', idx=2677)
tensor([[0.]])
